services:
  server:
    build: .
    ports:
      - "4000:4000"
  client:
    build: ./src
    ports:
      - "8080:8080"
    env_file:
      - ./src/.env
  redis:
    image: "redis:alpine"

networks:
  mynetwork:
    driver: bridge
    external: true
