services:
  server:
    build: ../../
    env_file:
      - ./src/.env
    ports:
      - "4000:4000"
  client:
    build: ./src/.env
    ports:
      - "8080:3000"
    env_file:
      - ./src/.env
    depends_on:
      - server
  redis:
    image: "redis:alpine"

networks:
  mynetwork:
    driver: bridge
    external: true
